spring.application.name=customer-support-chatbot-springai
server.port=8080

# Gemini API configuration
gemini.api.key=<<add your API key here>>
logging.level.org.springframework.web.reactive.function.client=DEBUG
